### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by followben** [ketgo/py-abac#26]
I need to implement a distributed auth system where policies are defined/ maintained in a central service while decision/ enforcement is delegated. Requests pass thru a central gateway that has access to the IAM system (to authenticate tokens and enrich the request with an ACL and info about the bearer) but not data from the destination system.

py-abac looks particularly nice because policies are succinct and serialisable. I could find/ match applicable policies in our gateway (on say subject and context attributes) and add them to the request and let the backend application enforce them. Best part of all I can use the same library in both places and not require further inter-service communication.

Is this library used in a production application anywhere do you know? Would you welcome pull requests to be able to achieve the above? I'm fairly new to ABAC, but I was thinking either:
- create a new PAP that takes a storage instance and is able to match/ export a list of policies, or
- extend the PDP to do the same

Appreciate your efforts so far... if nothing else it's helped to see how someone else has approached this design in Python :)

And thanks in advance for your thoughts!

**Comment by ketgo** [comment]
Hi @followben 

Thanks for considering the py-abac library for your application! The project is being maintained and pull requests are always welcomed. Currently any new features are added on request basis. Please feel free to reach out to me, open a ticket on github, and/or send PR :)

I am not aware of the name of applications using the library in production but I do know there are few since I have previously gotten queries regarding the same.

**Comment by followben** [comment]
Thanks @ketgo - what & where do you think the best api would be to query and return applicable Policy objects? Best to extend the current PDP implementation or in a new class?

**Comment by ketgo** [comment]
Hi @followben, apologies for the late reply. Currently I am on commute for a few days and have bad internet connection. Regarding your question, I think creating a PAP which takes an instance of storage makes better sense. However, you would need to share the backend storage with the PDP since it would need it to retrieve policies for evaluation.
